### ISSUE TITLE
Not Working on Protocolize Update

### ISSUE THREAD

**Issue by belphegorspn** [Matt-MX/ServerGUI#4]
After updating protocolize to support 1.19.1, /lobby and /server does not work anymore.

After doing /server command and picking a server, it sends errors in the console

[21:04:14 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[21:04:14 ERROR] [Protocolize]: Protocolize 2.2.2:374
[21:04:14 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[21:04:14 ERROR] [Protocolize]: InboundConnection: [connected player] belphygore (/49.145.38.251:43889), ServerConnection: null
[21:04:14 ERROR] [Protocolize]: Protocol version: 1.18.2
[21:04:14 ERROR]: java.lang.NoSuchMethodError: 'dev.simplix.protocolize.api.item.ItemStack dev.simplix.protocolize.api.inventory.InventoryClick.clickedItem()'
[21:04:14 ERROR]:       at com.mattmx.servergui.gui.ServerSelector.onClick(ServerSelector.java:41)
[21:04:14 ERROR]:       at com.mattmx.servergui.util.InventoryBuilder.onClickCancel(InventoryBuilder.java:111)
[21:04:14 ERROR]:       at dev.simplix.protocolize.data.listeners.ClickWindowListener.lambda$packetReceive$0(ClickWindowListener.java:48)
[21:04:14 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[21:04:14 ERROR]:       at dev.simplix.protocolize.data.listeners.ClickWindowListener.packetReceive(ClickWindowListener.java:48)
[21:04:14 ERROR]:       at dev.simplix.protocolize.velocity.providers.VelocityPacketListenerProvider.lambda$handleInboundPacket$2(VelocityPacketListenerProvider.java:160)
[21:04:14 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[21:04:14 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[21:04:14 ERROR]:       at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
[21:04:14 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
[21:04:14 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[21:04:14 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[21:04:14 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[21:04:14 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:04:14 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[21:04:14 ERROR]:       at dev.simplix.protocolize.velocity.providers.VelocityPacketListenerProvider.handleInboundPacket(VelocityPacketListenerProvider.java:158)
[21:04:14 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:83)
[21:04:14 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:32)
[21:04:14 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:04:14 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89)
[21:04:14 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:04:14 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:04:14 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:04:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[21:04:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:04:14 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:04:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:04:14 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:04:14 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[21:04:14 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[21:04:14 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[21:04:14 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[21:04:14 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:04:14 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:04:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by xrh0905** [comment]
See [#6](https://github.com/Matt-MX/ServerGUI/pull/6)
